[package]
name = "d2l"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.13.0"
rand ="0.8.5"
polars = "0.30.0"
plotters = "0.3.5"
minifb = "0.24.0"
